#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)
require 'rpn_calc/cli'

Signal.trap('INT') do
  warn(' RPN calculator interrupted!')
  exit(1)
end

begin
  RpnCalc::CLI.start
rescue RpnCalc::CLI::Error => err
  puts "FATAL ERROR: #{err.message}"
  exit(1)
end
